### ISSUE TITLE
OSError: Load averages are unobtainable

### ISSUE THREAD

**Issue by jr0d** [jr0d/mercury#4]
Pong thread dies with:

```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
  File "/root/mercury/src/mercury-agent/mercury/agent/pong.py", line 99, in _spawn
  File "/root/mercury/src/mercury-agent/mercury/agent/pong.py", line 92, in run
  File "/root/mercury/src/mercury-agent/mercury/agent/pong.py", line 78, in pong
OSError: Load averages are unobtainable
```

**Comment by atzshjh** [comment]
hi, how did you solve it? I encounter it recently. thx
